services:
  # MySQL Database (Development with seed data)
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}-dev
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_dev_data:/var/lib/mysql
      # TODO: Re-enable seed data after migrations
      # - ./scripts/seed:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ${REDIS_CONTAINER_NAME}-dev
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 5

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PHPMYADMIN_CONTAINER_NAME}-dev
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${PHPMYADMIN_PASSWORD}
    depends_on:
      - mysql

volumes:
  mysql_dev_data:
  redis_dev_data: